language: node_js

compiler: gcc
sudo: false

os:
- linux
- osx

env:
  global:
    - secure: M9jZQUD6Ly0JM1/DMqOG1pOzXbMSFAz1pDPzhqHOpA8PYSh9DwcJf8o+nZWyBZmcszzMbsPdTEd328MNG1PhJEK7SWxozRnD4QiXVNk8v9QKqRUrXZb6Px8LLyoEGqCFslp9UuGDJeqRghDSlNJPfcYgHfj+Wzq9pjGw1Jx5Oxfd0GFnvwT3gKscRYkTCykbh10TVCqXXRK+8FCQw1m5XpIqSSpkWYAyGNFxbtdJgIhB2z7D94U783D93HCXhFXarlOMAbkLieRd5y3g6zXF7iUCji/JniEDqesmCqTEbZAAJEW9OC6aCQda8kro9+JS1KXMGAEVzZmsOdKzn2renge/ICXdgqEhxxJsbYYcs14ytmKhkSjjeSuAghMA8lGUWHZbr+FSe0ijQdqBN+sBCKpwnJBSnPvlLJOI+CiqUf4S2C7SaJJu5eb6TtkuKvUTbGhPCw0AJsSHviOajlPrUriOcNk6SsumM7LOJui1F3cyPZXfw8bplheLHGFPb72AxF5PzYiyfkmE3YZDnIdbrlGJmyebBUa9Ikl34op5yRVsJODvqO+zqcw5FRC8+StTb+wov3Yvf+IP/M/49OxqV7JR1Yk4N0quF3j/PGGn4PQPnOTEzh+dnOGVg4EH6KCxyv+2Qx+TRPfOB4LWy6aJ57jLbvt6WhXnfVSpnuJ2QuQ=

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    
sudo: false

before_install:
- $CXX --version
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-4.8";
    export CXX="g++-4.8";
    export LINK="gcc-4.8";
    export LINKXX="g++-4.8";
  fi
- nvm --version
- node --version
- npm --version
- gcc --version
- g++ --version

before_script:
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')

install:
- npm install

script:
- npm test
- if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then node-pre-gyp package && node-pre-gyp-github
  publish --release; fi;

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules